# Generated by Django 2.2.6 on 2019-10-07 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RestIT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='email',
            field=models.EmailField(default='xyz@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='firstName',
            field=models.TextField(default='John', max_length=30),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='lastLoginDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='lastName',
            field=models.TextField(default='Kennedy', max_length=30),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='login',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='signUpDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 7, 17, 40, 53, 755141, tzinfo=utc)),
        ),
    ]
