# Generated by Django 2.2.6 on 2019-10-07 21:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RestIT', '0002_auto_20191007_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='signUpDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 7, 21, 7, 1, 130004, tzinfo=utc)),
        ),
    ]
