# Generated by Django 2.2.6 on 2019-10-08 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RestIT', '0003_auto_20191007_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='signUpDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 8, 6, 48, 18, 296933, tzinfo=utc)),
        ),
    ]
